title: ViennaPS Documentation
description: The documentation for ViennaPS
theme: just-the-docs
color_scheme: iue

url: https://viennatools.github.io/ViennaPS/
logo: "/assets/images/logo.png"
# Favicon
favicon_ico: "/assets/images/logo.png"

aux_links:
  "ViennaPS on Github": 
    - "//github.com/ViennaTools/ViennaPS"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts:
  warning:
    title: Warning
    color: yellow
  danger:
    title: Danger
    color: red
  note:
    title: Note
    color: blue